# add & commit
alias g="git"
alias gv="git --version"
alias ga="git add"
alias gaa="git add --all"
alias gapa="git add --patch"
alias gc="git commit -v"
alias gc!="git commit -v --amend"
alias gca="git commit -v -a"
alias gca!="git commit -v -a --amend"
alias gcan!="git commit -v -a --no-edit"
alias gcans!="git commit -v -a -s --no-edit --amend"
alias gcam="git commit -a -m"
alias gcsm="git commit -s -m"
alias gcmsg="git commit -m"
alias gcs="git commit -S"

# checkout & branch
alias gs="git switch"
alias gsd="git switch dev"
alias gsm="git switch main"
alias gsb="git switch -b"
alias gco="git checkout"
alias gcd="git checkout dev"
alias gcm="git checkout main"
alias gcb="git checkout -b"
alias gb="git branch"
alias gbr="git branch -r"
alias gba="git branch -a"
alias gbnm="git branch --no-merged"
alias ggsup="git branch --set-upstream-to=origin/"

# logs
alias gl="git log"
alias glg="git log --stat --max-count=10"
alias glgg="git log --graph --max-count=10"
alias glgga="git log --graph --decorate --all"
alias glo="git log --oneline --decorate --color"
alias glog="git log --oneline --decorate --color --graph"
alias glp="git log --pretty=$1"

# clone, push, fetch, pll & merge
alias gcl="git clone --recursive"
alias gcld="git clone --depth 1"
alias gp="git push"
alias ggp="git push origin \$(git rev-parse --abbrev-ref HEAD)"
alias gsup="git push --set-upstream origin \$(git rev-parse --abbrev-ref HEAD)"
alias gpoat="git push origin --all && git push origin --tags"
alias gf="git fetch"
alias gfa="git fetch --all --prune"
alias gfo="git fetch origin"
alias ggl="git pull"
alias gpull="git pull origin \$(git rev-parse --abbrev-ref HEAD)"
alias gpur="git pull --rebase origin \$(git rev-parse --abbrev-ref HEAD)"
alias glum="git pull upstream master"
alias gup="git pull --rebase"
alias gpnp="git pull origin \$(git rev-parse --abbrev-ref HEAD) && git push origin \$(git rev-parse --abbrev-ref HEAD)"
alias gm="git merge"
alias gmom="git merge origin/main"
alias gmt="git mergetool --no-prompt"
alias gmtvim="git mergetool --no-prompt --tool=vimdiff"
alias gmum="git merge upstream/main"
alias gma="git merge --abort"

# remotes
alias gr="git remote"
alias grv="git remote -v"
alias grmv="git remote rename"
alias grrm="git remote remove"
alias grset="git remote set-url"
alias grup="git remote update"

# rewriting history
alias grbi="git rebase -i"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grbs="git rebase --skip"
alias gcp="git cherry-pick"
alias gcpa="git cherry-pick --abort"
alias gcpc="git cherry-pick --continue"
